name: 'aws-nuke'

on:
  # Enable manual runs
  workflow_dispatch:
    inputs:
      delete:
        description: 'Set to "true" to actually delete stuff'
        required: true
        default: 'true'
        
  # Enable pull request for testing
  pull_request: 
    types: [opened, synchronize, reopened]

  # Nuke testing account nightly
  schedule:
    # Run at noon UTC, 4 or 5am PT
    - cron:  '0 12 * * *'

jobs:
  # Run aws-nuke simulation (don't actually delete anything)
  dry-run:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || ( github.event_name == 'workflow_dispatch' && github.event.inputs.delete != 'true' )
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: aws-nuke
        uses: "docker://quay.io/rebuy/aws-nuke:v2.25.0"
        with:
          args: "--config .github/nuke-config.yml --force"
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

  # Run aws-nuke "for reals" (delete everything)
  no-dry-run:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || ( github.event_name == 'workflow_dispatch' && github.event.inputs.delete == 'true' )
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: aws-nuke
        uses: "docker://quay.io/rebuy/aws-nuke:v2.25.0"
        with:
          args: "--config .github/nuke-config.yml --force --no-dry-run"
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
